from enum import StrEnum, Enum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    DOCTOR = "DOCTOR"
    OPERATOR = "OPERATOR"


class StudyStatus(StrEnum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    READY = "READY"
    UNSUPPORTED = "UNSUPPORTED"
    FAILED = "FAILED"


class AnalysisJobStatus(StrEnum):
    QUEUED = "QUEUED"
    PREPROCESSING = "PREPROCESSING"
    ANALYZING = "ANALYZING"
    POSTPROCESSING = "POSTPROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AnalysisResultStatus(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    FAIL = "FAIL"
    CANNOT_ASSESS = "CANNOT_ASSESS"


class ModelVersionStatus(StrEnum):
    EXPERIMENTAL = "EXPERIMENTAL"
    CANDIDATE = "CANDIDATE"
    PRODUCTION = "PRODUCTION"
    RETIRED = "RETIRED"




class AuditEventType(StrEnum):
    USER_LOGIN = "USER_LOGIN"
    DICOM_DEIDENTIFIED = "DICOM_DEIDENTIFIED"
    STUDY_CREATED = "STUDY_CREATED"
    ANNOTATION_CREATED = "ANNOTATION_CREATED"
    CONSENSUS_CREATED = "CONSENSUS_CREATED"
    CONSENSUS_APPROVED = "CONSENSUS_APPROVED"
    CONSENSUS_REJECTED = "CONSENSUS_REJECTED"
    DATASET_SNAPSHOT_CREATED = "DATASET_SNAPSHOT_CREATED"

    ANALYSIS_CREATED = "ANALYSIS_CREATED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"

    AI_PROVIDER_SELECTED = "AI_PROVIDER_SELECTED"
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"

    QUALITY_EVALUATED = "QUALITY_EVALUATED"
    DECISION_CREATED = "DECISION_CREATED"

    ANALYSIS_FAILED = "ANALYSIS_FAILED"

    JOB_RETRIED = "JOB_RETRIED"
    DLQ_REQUEUED = "DLQ_REQUEUED"


class QCAnalysisStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    FAILED = "FAILED"



class AnnotationConsensusStatus(str, Enum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
