"""add qc analyses table

Revision ID: 4d1aa01d01ab
Revises: a27542b79afb
Create Date: 2026-09-13 19:16:04.694854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1aa01d01ab'
down_revision: Union[str, Sequence[str], None] = 'a27542b79afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_analyses',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'COMPLETED', 'REVIEW_REQUIRED', 'FAILED', name='qc_analysis_status', native_enum=False), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_qc_analyses_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_analyses'))
    )
    op.create_index(op.f('ix_qc_analyses_status'), 'qc_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_qc_analyses_study_id'), 'qc_analyses', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_analyses_study_id'), table_name='qc_analyses')
    op.drop_index(op.f('ix_qc_analyses_status'), table_name='qc_analyses')
    op.drop_table('qc_analyses')
    # ### end Alembic commands ###
