"""initial domain schema

Revision ID: 6bcae1478771
Revises:
Create Date: 2026-09-13 09:54:29.991347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bcae1478771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('EXPERIMENTAL', 'CANDIDATE', 'PRODUCTION', 'RETIRED', name='model_version_status', native_enum=False), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('dataset_version', sa.String(length=255), nullable=True),
    sa.Column('weights_hash', sa.String(length=128), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_task'), 'model_versions', ['task'], unique=False)
    op.create_table('studies',
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'READY', 'UNSUPPORTED', 'FAILED', name='study_status', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('source_object_key', sa.String(length=1024), nullable=False),
    sa.Column('preview_object_key', sa.String(length=1024), nullable=True),
    sa.Column('dicom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies')),
    sa.UniqueConstraint('source_object_key', name=op.f('uq_studies_source_object_key'))
    )
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREPROCESSING', 'ANALYZING', 'POSTPROCESSING', 'COMPLETED', 'FAILED', name='analysis_job_status', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_analysis_jobs_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_study_id'), 'analysis_jobs', ['study_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_audit_events_study_id_studies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_study_id'), 'audit_events', ['study_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'REVIEW', 'FAIL', 'CANNOT_ASSESS', name='analysis_result_status', native_enum=False), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], name=op.f('fk_analysis_results_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_analysis_results_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_analysis_results_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results')),
    sa.UniqueConstraint('job_id', name=op.f('uq_analysis_results_job_id'))
    )
    op.create_index(op.f('ix_analysis_results_model_version_id'), 'analysis_results', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_status'), 'analysis_results', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_results_study_id'), 'analysis_results', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_study_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_status'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_model_version_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_audit_events_study_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_analysis_jobs_study_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_model_versions_task'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
