"""extend audit events entity tracking

Revision ID: a27542b79afb
Revises: 6bcae1478771
Create Date: 2026-09-13 18:19:34.076007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27542b79afb'
down_revision: Union[str, Sequence[str], None] = '6bcae1478771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('audit_events', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_column('audit_events', 'entity_id')
    op.drop_column('audit_events', 'entity_type')
    # ### end Alembic commands ###
